# Generated by Django 4.2.16 on 2024-11-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите картинку')),
                ('title', models.CharField(max_length=100, verbose_name='Введите название книги')),
                ('description', models.TextField(verbose_name='Введите описание книги')),
                ('price', models.FloatField(verbose_name='Введите цену книги')),
                ('published_data', models.DateField(verbose_name='Дата публикации')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Детектив', 'Детектив'), ('Роман', 'Роман'), ('Приключения', 'Приключения')], max_length=100, verbose_name='Жанр книги')),
                ('mail', models.EmailField(max_length=254, verbose_name='Введите почту автора')),
                ('author', models.CharField(max_length=100, verbose_name='Введите автора книги')),
                ('audio_book', models.URLField(verbose_name='Введите ссылку на аудиокн')),
            ],
        ),
    ]
