# Generated by Django 4.2.16 on 2024-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_books_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='stock_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество в наличии'),
        ),
    ]
